### ISSUE TITLE
App no longer starts

### ISSUE THREAD

**Issue by jamerst** [rokartur/Micmute#2]
Yesterday macOS decided to incorrectly detect the app as malware. Even after overriding the malware protection the app still won't start.

Trying to start it just results in a generic "The application Micmute.app can't be opened" error. A more specific error can be obtained by attempting to start it from the command line:

```
The application /Applications/Micmute.app cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000013ddbf0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by yazenhalid** [comment]
I faced same issue

**Comment by rokartur** [comment]
I fixed it, I will have to do something about it. The best way is to buy a developer's license, only it's a bit expensive, so I'm thinking of making this program licensed in the future to make it profitable. Currently I will still renew the program to make it work 🫡
